[controllers]
jenkins-controller ansible_host=10.10.1.10 ansible_user=ubuntu

[shared-services]
sonarqube ansible_host=10.10.1.20 ansible_user=ubuntu
nexus ansible_host=10.10.1.21 ansible_user=ubuntu
vault ansible_host=10.10.1.22 ansible_user=ubuntu
ansible ansible_host=10.10.1.23 ansible_user=ubuntu
