{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.serviceMonitor.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  endpoints:
    - port: http
{{- end }}
