pipeline {
  agent any
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('Build') { steps { sh 'echo build' } }
    stage('Test') { steps { sh 'echo test' } }
    stage('Sonar') { steps { sh 'echo sonar' } }
    stage('Trivy') { steps { sh 'echo trivy' } }
    stage('Docker Build') { steps { sh 'echo docker build' } }
    stage('Deploy') { steps { sh 'echo deploy' } }
  }
}
